apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
  labels:
    app: my-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      volumes:
      - name: app-storage
        emptyDir: {}
      containers:
      - name: my-app
        image: my-app:1.0.0
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: app-storage
          mountPath: /app/data
